// Mapping of department codes to full names
export const departmentNames: Record<string, string> = {
  'ARMENST': 'Armenian Studies',
  'MODGRK': 'Modern Greek',
  'VIETNAM': 'Vietnamese',
  'WSTAFRCN': 'West African Languages',
  'FT': 'Film and Television',
  'JAPNLIT': 'Japanese Literature',
  'SWEDISH': 'Swedish',
  'TURKISH': 'Turkish',
  'ISLAMCIV': 'Islamic Civilization',
  'JAPAN': 'Japanese',
  'RSRA': 'Russian and Slavic Studies',
  'SANSKRIT': 'Sanskrit',
  'CHNSE': 'Chinese',
  'HIND-URD': 'Hindi-Urdu',
  'CLASPHIL': 'Classical Philosophy',
  'PORTUG': 'Portuguese',
  'GHHP': 'Global Health and Health Policy',
  'CPB': 'Chemical and Physical Biology',
  'ITAL': 'Italian',
  'EAFM': 'East Asian Film and Media',
  'CHNSHIS': 'Chinese History',
  'RUSS': 'Russian',
  'YORUBA': 'Yoruba',
  'CHNSLIT': 'Chinese Literature',
  'WOMGEN': 'Studies of Women, Gender, and Sexuality',
  'SOC-STD': 'Social Studies',
  'ARABIC': 'Arabic',
  'CELTIC': 'Celtic Languages and Literatures',
  'CLASARCH': 'Classical Archaeology',
  'GREEK': 'Greek',
  'HUMAN': 'Humanities',
  'SLAVIC': 'Slavic Languages and Literatures',
  'ENGLISH': 'English',
  'EXPOS': 'Expository Writing',
  'EASTD': 'East Asian Studies',
  'HISTSCI': 'History and Science',
  'GERMAN': 'Germanic Languages and Literatures',
  'EMR': 'Ethnicity, Migration, Rights',
  'NEURO': 'Neuroscience',
  'KOREAN': 'Korean',
  'MBB': 'Molecular and Cellular Biology',
  'LATIN': 'Latin',
  'GENETIC': 'Genetics',
  'ROM-STD': 'Romance Languages and Literatures',
  'AMHARIC': 'Amharic',
  'AFRAMER': 'African and African American Studies',
  'HEB': 'Hebrew',
  'ANE': 'Ancient Near Eastern Studies',
  'HAA': 'History of Art and Architecture',
  'HIST-LIT': 'History and Literature',
  'MODMDEST': 'Modern Middle Eastern Studies',
  'SCRB': 'Human Developmental and Regenerative Biology',
  'EDST': 'Education Studies',
  'PSY': 'Psychology',
  'ANTHRO': 'Anthropology',
  'AFVS': 'Art, Film, and Visual Studies',
  'E-PSCI': 'Earth and Planetary Sciences',
  'SPANSH': 'Spanish',
  'FOLKMYTH': 'Folklore and Mythology',
  'SWAHILI': 'Swahili',
  'RELIGION': 'Comparative Study of Religion',
  'HIST': 'History',
  'COMPLIT': 'Comparative Literature',
  'TDM': 'Theater, Dance, and Media',
  'FRENCH': 'French',
  'MEDVLSTD': 'Medieval Studies',
  'MUSIC': 'Music',
  'CLS-STDY': 'Classics',
  'FYSEMR': 'First-Year Seminars',
  'ASTRON': 'Astrophysics',
  'JEWISHST': 'Jewish Studies',
  'ESE': 'Environmental Science and Engineering',
  'PHIL': 'Philosophy',
  'GOV': 'Government',
  'SOCIOL': 'Sociology',
  'FRSEMR': 'Freshman Seminars',
  'MOD-HEB': 'Modern Hebrew',
  'OEB': 'Integrative Biology',
  'MICROBI': 'Microbiology',
  'PHYSICS': 'Physics',
  'ECON': 'Economics',
  'HBTM': 'Human Evolutionary Biology',
  'CHEM': 'Chemistry',
  'MATH': 'Mathematics',
  'BE': 'Biomedical Engineering',
  'LING': 'Linguistics',
  'APPHY': 'Applied Physics',
  'STAT': 'Statistics',
  'ENG-SCI': 'Engineering Sciences',
  'NEC': 'Near Eastern Languages and Civilizations',
  'AAAS': 'African and African American Studies',
  'CELLBIO': 'Cell Biology',
  'BPH': 'Biophysics',
  'MCB': 'Molecular and Cellular Biology',
  'IMMUN': 'Immunology',
  'PERSIAN': 'Persian',
  'COMPSCI': 'Computer Science',
  'NEUROBIO': 'Neurobiology',
  'LIFESCI': 'Life Sciences',
  'APMTH': 'Applied Mathematics',
  'IGBO': 'Igbo',
  'QSE': 'Quantitative Social Science',
  'HLTHPOL': 'Health Policy',
  'GENED': 'General Education',
  'ESPP': 'Environmental Science and Public Policy',
  'BIOSTAT': 'Biostatistics',
  'BCMP': 'Biological Chemistry and Molecular Pharmacology',
  'PHYSCI': 'Physical Sciences',
  'MED-SCI': 'Medical Sciences',
  'VIROLOGY': 'Virology',
  'APCOMP': 'Applied Computation',
  'SHBT': 'Speech and Hearing Bioscience and Technology',
  'BBS': 'Biological and Biomedical Sciences',
};

// Helper function to get department name from code
export function getDepartmentName(code: string): string {
  return departmentNames[code] || code;
}

