// lib/divisionMapping.ts
// Maps department codes to their academic divisions

export type Division = 'Humanities' | 'STEM' | 'Social Sciences';

const divisionMap: Record<string, Division> = {
  // STEM
  'COMPSCI': 'STEM',
  'MATH': 'STEM',
  'STAT': 'STEM',
  'PHYSICS': 'STEM',
  'CHEM': 'STEM',
  'ASTRON': 'STEM',
  'ENG-SCI': 'STEM',
  'APPHY': 'STEM',
  'APMTH': 'STEM',
  'BE': 'STEM',
  'ESE': 'STEM',
  'E-PSCI': 'STEM',
  'MCB': 'STEM',
  'MBB': 'STEM',
  'OEB': 'STEM',
  'NEURO': 'STEM',
  'NEUROBIO': 'STEM',
  'LIFESCI': 'STEM',
  'SCRB': 'STEM',
  'GENETIC': 'STEM',
  'CELLBIO': 'STEM',
  'IMMUN': 'STEM',
  'BPH': 'STEM',
  'BIOSTAT': 'STEM',
  'BCMP': 'STEM',
  'MICROBI': 'STEM',
  'VIROLOGY': 'STEM',
  'PHYSCI': 'STEM',
  'MED-SCI': 'STEM',
  'APCOMP': 'STEM',
  'QSE': 'STEM',
  'SHBT': 'STEM',
  'BBS': 'STEM',
  'HBTM': 'STEM',

  // Social Sciences
  'ECON': 'Social Sciences',
  'GOV': 'Social Sciences',
  'PSY': 'Social Sciences',
  'SOCIOL': 'Social Sciences',
  'ANTHRO': 'Social Sciences',
  'SOC-STD': 'Social Sciences',
  'EDST': 'Social Sciences',
  'HLTHPOL': 'Social Sciences',
  'GHHP': 'Social Sciences',
  'ESPP': 'Social Sciences',
  'EMR': 'Social Sciences',
  'LING': 'Social Sciences',

  // Humanities
  'ENGLISH': 'Humanities',
  'HIST': 'Humanities',
  'PHIL': 'Humanities',
  'FRENCH': 'Humanities',
  'GERMAN': 'Humanities',
  'SPANSH': 'Humanities',
  'ITAL': 'Humanities',
  'PORTUG': 'Humanities',
  'RUSS': 'Humanities',
  'CHNSE': 'Humanities',
  'JAPAN': 'Humanities',
  'KOREAN': 'Humanities',
  'ARABIC': 'Humanities',
  'PERSIAN': 'Humanities',
  'HEB': 'Humanities',
  'MOD-HEB': 'Humanities',
  'LATIN': 'Humanities',
  'GREEK': 'Humanities',
  'CLASARCH': 'Humanities',
  'CLASPHIL': 'Humanities',
  'CLS-STDY': 'Humanities',
  'HAA': 'Humanities',
  'MUSIC': 'Humanities',
  'TDM': 'Humanities',
  'AFVS': 'Humanities',
  'FT': 'Humanities',
  'COMPLIT': 'Humanities',
  'RELIGION': 'Humanities',
  'HISTSCI': 'Humanities',
  'HIST-LIT': 'Humanities',
  'FOLKMYTH': 'Humanities',
  'MEDVLSTD': 'Humanities',
  'HUMAN': 'Humanities',
  'EXPOS': 'Humanities',
  'GENED': 'Humanities',
  'FYSEMR': 'Humanities',
  'FRSEMR': 'Humanities',
  'WOMGEN': 'Humanities',
  'AFRAMER': 'Humanities',
  'AAAS': 'Humanities',
  'EASTD': 'Humanities',
  'MODMDEST': 'Humanities',
  'ISLAMCIV': 'Humanities',
  'NEC': 'Humanities',
  'ANE': 'Humanities',
  'JEWISHST': 'Humanities',
  'ROM-STD': 'Humanities',
  'RSRA': 'Humanities',
  'SLAVIC': 'Humanities',
  'CELTIC': 'Humanities',
  'ARMENST': 'Humanities',
  'MODGRK': 'Humanities',
  'VIETNAM': 'Humanities',
  'WSTAFRCN': 'Humanities',
  'JAPNLIT': 'Humanities',
  'SWEDISH': 'Humanities',
  'TURKISH': 'Humanities',
  'SANSKRIT': 'Humanities',
  'HIND-URD': 'Humanities',
  'EAFM': 'Humanities',
  'CHNSHIS': 'Humanities',
  'YORUBA': 'Humanities',
  'CHNSLIT': 'Humanities',
  'AMHARIC': 'Humanities',
  'SWAHILI': 'Humanities',
  'IGBO': 'Humanities',
};

export const getDivision = (departmentCode: string): Division => {
  return divisionMap[departmentCode] || 'Humanities'; // Default to Humanities if not found
};

export const divisionColors: Record<Division, string> = {
  'Humanities': '#DC143C',      // Crimson red
  'STEM': '#3B82F6',            // Blue
  'Social Sciences': '#22C55E', // Green
};
